### ISSUE TITLE
[FE] react 초기 설정

### ISSUE THREAD

**Issue by j8won** [JNU-econovation/CoNoE#1]
## Description
react 초기 설정

## Todo
- [x] install  `react-router-dom`, `styled-components`, `styled-reset`,  `axios`, `prop-types`, `prettier`
- [x] react router 설정
- [x] prettier 설정
- [x] styled-reset 설정
